version: '2'

services:
    odsupercomponent:
        image: ${IMAGE}
        network_mode: host
        volumes:
        - .:/opt/opendlv.data
        command: "/opt/od4/bin/odsupercomponent --cid=${CID} --verbose=1 --configuration=/opt/opendlv.data/configuration"
    odcockpit:
        image: ${IMAGE}
        network_mode: host
        environment:
        - DISPLAY=$DISPLAY
        volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
        - .:/opt/opendlv.data
        - ~/recordings:/opt/Recordings
        ipc: host
        user: odv
        depends_on:
            - odsupercomponent
        command: "/opt/od4/bin/odcockpit --cid=${CID}"

    cfsd18-sensation-attention:
        image: attention:test
        network_mode: "host"
        ipc: host
        volumes:
        - .:/opt/files
        command: "cfsd18-sensation-attention --cid=${CID} --cidCan=219 --id=117 --xBoundary=4 --yBoundary=25 --zUpperBoundary=0.6
        --groundClusterDistanceThreshold=0.3 --groundClusterSizeThreshold=60 --connectDistanceThreshold=0.15 --minNumOfPointsForCone=3
        --maxNumOfPointsForCone=300 --coneRadiusThreshold=0.15 --zRangeThreshold=0.0 --inlierRangeThreshold=0.06 --dotThreshold=0.1
        --inlierFoundThreshold=500 --numberOfIterations=30 --stateMachineId=1401 --readyStateMachine=0"
