version: '2'

services:
    odsupercomponent:
        image: ${IMAGE}
        network_mode: host
        volumes:
        - .:/opt/opendlv.data
        command: "/opt/od4/bin/odsupercomponent --cid=${CID} --verbose=1 --configuration=/opt/opendlv.data/configuration"
    odcockpit:
        image: ${IMAGE}
        network_mode: host
        environment:
        - DISPLAY=$DISPLAY
        volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
        - .:/opt/opendlv.data
        - ~/recordings:/opt/Recordings
        ipc: host
        user: odv
        depends_on:
            - odsupercomponent
        command: "/opt/od4/bin/odcockpit --cid=${CID}"

    cfsd18-sensation-attention:
        image: "attention:test"
        network_mode: "host"
        ipc: host
        command: "cfsd18-sensation-attention --cid=${CID} --verbose --id=1 --xBoundary=2 --yBoundary=10 --groundLayerZ=-0.17 --coneHeight=0.4 --connectDistanceThreshold=0.8 --layerRangeThreshold=0.06 --minNumOfPointsForCone=2 --maxNumOfPointsForCone=80 --farConeRadiusThreshold=0.2 --nearConeRadiusThreshold=0.25 --zRangeThreshold=0.08 --inlierRangeThreshold=0.1 --dotThreshold=0.3 --inlierFoundThreshold=80 --numberOfIterations=10"

#    proxy-velodyne16:
#        image: chalmersrevere/opendlv-device-lidar-vlp16-multi:v0.0.6
#        network_mode: "host"
#        volumes:
#            - .:/opt/opendlv.data
#        ipc: host
#        # user: odv
#        working_dir: "/opt/opendlv.data"
#        command: "opendlv-device-lidar-vlp16 --vlp16_ip=0.0.0.0 --vlp16_port=2368 --cid=${CID}"
